---
title: "FIFA 20 Predicting Player Value"
author: "Akshit Jain"
date: "3/28/2020"
output: pdf_document
---

```{r setup, include=FALSE}
library(dplyr)
library(tidyr)
library(stringr)
library(purrr)
library(tibble)
library(data.table)
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
fifa20 <- fread("~/Desktop/Northeastern-University/SML/FIFA-Player-Assessment-Model-and-Analytics/Datasets/players_20.csv")
fifa20 <- as_tibble(fifa20)
```

# Data cleaning

```{r}
# remove columns that are not required for modeling
updated_fifa20 <- fifa20 %>% select(-player_url, -long_name, -dob, -real_face, -player_tags, 
                                    -loaned_from, -joined, -player_positions, -contract_valid_until,
                                    -nation_position, -nation_jersey_number, -player_traits, -gk_diving,
                                    -gk_handling, -gk_kicking, -gk_reflexes, -gk_speed, -gk_positioning,
                                    -goalkeeping_diving, -goalkeeping_handling, -goalkeeping_kicking,
                                    -goalkeeping_positioning, -goalkeeping_reflexes, 
                                    -ls, -st, -rs, -lw, -lf, -cf, -rf, -rw, -lam, -cam, -ram, 
                                    -lm, -lcm, -cm, -rcm, -rm, -lwb, -ldm, -cdm, -rdm, -rwb, 
                                    -lb, -lcb, -cb, -rcb, -rb)

# remove oberservations that have missing values (NOT processing Goalkeepers)
clean_fifa20 <- na.omit(updated_fifa20)
clean_fifa20
```

```{r}
df <- sample_n(clean_fifa20, nrow(clean_fifa20))
df <- df %>% select(-short_name, -nationality, -club, -body_type, -team_jersey_number, -team_position)
```

# Fit a linear model for player value
```{r}
value.fit <- lm(value_eur ~., data=df)
summary(value.fit)
names(value.fit)
```

# Exploring predictors that have an impact on player value
```{r}

# overall
fit_overall <- lm(log(value_eur) ~ log(overall), data = df)
summary(fit_overall)

plot(log(value_eur) ~ log(overall), data = df)
abline(fit_overall, col="red")

# potential
fit_potential <- lm(log(value_eur) ~ log(potential), data = df)
summary(fit_potential)

plot(log(value_eur) ~ log(potential), data = df)
abline(fit_potential, col="red")


# release_clause_eur
fit_rc <- lm(value_eur ~ release_clause_eur, data = df)
summary(fit_rc)

plot(value_eur ~ release_clause_eur, data = df)
abline(fit_rc, col="red")

# attacking_volleys
fit_av <- lm(log(value_eur) ~ log(attacking_volleys), data = df)
summary(fit_av)

plot(log(value_eur) ~ log(attacking_volleys), data = df)
abline(fit_av, col="red")

```

# Feature Selection: Forward Stepwise Selection
```{r}

df <- sample_n(clean_fifa20, nrow(clean_fifa20))
df <- df %>% select(-short_name, -nationality, -club, -body_type, -team_jersey_number, -team_position)

library(leaps)
regfit.fwd=regsubsets(value_eur~.,df, method="forward")
reg.summary <- summary(regfit.fwd)
reg.summary
```

```{r}
par(mfrow=c(2,2))

plot(reg.summary$rss,xlab="Number of Variables",ylab="RSS",type="l")

plot(reg.summary$adjr2,xlab="Number of Variables",ylab="Adjusted RSq",type="l")
which.max(reg.summary$adjr2)
points(8,reg.summary$adjr2[8], col="red",cex=2,pch=20)

plot(reg.summary$cp,xlab="Number of Variables",ylab="Cp",type='l')
which.min(reg.summary$cp)
points(8,reg.summary$cp[8],col="red",cex=2,pch=20)

which.min(reg.summary$bic)
plot(reg.summary$bic,xlab="Number of Variables",ylab="BIC",type='l')
points(8,reg.summary$bic[8],col="red",cex=2,pch=20)

```

```{r}
plot(regfit.fwd,scale="r2")
plot(regfit.fwd,scale="adjr2")
plot(regfit.fwd,scale="Cp")
plot(regfit.fwd,scale="bic")
```

```{r}
coef(regfit.fwd, 8)
```
